export const GET_AIRPORTS_INFO = "GET_AIRPORTS_INFO";
export const LOAD_MORE_AIRPORTS = "LOAD_MORE_AIRPORTS";
export const RESET_AIRPORTS = "RESET_AIRPORTS";
export const API_FAILURE = "API_FAILURE";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const LOAD_EXISTED_AIRPORTS = 'LOAD_EXISTED_AIRPORTS'
